# Generated by Django 5.1.7 on 2025-04-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Meню'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
    ]
