# Generated by Django 5.1.7 on 2025-04-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_menuitem_options_remove_menuitem_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Меню'},
        ),
    ]
