# Generated by Django 5.1.7 on 2025-05-20 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='people_count',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date(2025, 5, 20), verbose_name='Дата брони'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_number',
            field=models.PositiveSmallIntegerField(default=datetime.date(2025, 5, 20), verbose_name='Номер столика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Время брони'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
